# Generated by Django 2.0.2 on 2018-04-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0005_auto_20180407_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_sql', models.TextField()),
                ('is_successful', models.BooleanField(default=False)),
                ('fail_count', models.IntegerField(default=0)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
